[build]
  base = "Desktop/tville_transit/thomasville-shuttle"
  command = "npm run build"
  publish = "Desktop/tville_transit/thomasville-shuttle/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
